# Generated by Django 5.0.14 on 2026-06-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_accepted_terms',
            field=models.BooleanField(default=False),
        ),
    ]
