# Generated by Django 5.0.14 on 2026-06-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_has_accepted_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ORGANIZER', 'Organizador'), ('PARTICIPANT', 'Participante'), ('JUDGE', 'Jurado')], default='PARTICIPANT', max_length=20),
        ),
    ]
