# Generated by Django 5.0.14 on 2026-06-10 02:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='judges',
            field=models.ManyToManyField(blank=True, related_name='hackathons_to_judge', to=settings.AUTH_USER_MODEL),
        ),
    ]
